/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSubmissionsRouteImport } from './routes/_authed.submissions'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedReportsRouteImport } from './routes/_authed.reports'
import { Route as AuthedPropertiesRouteImport } from './routes/_authed.properties'
import { Route as AuthedProjectsRouteImport } from './routes/_authed.projects'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed.onboarding'
import { Route as AuthedJobsRouteImport } from './routes/_authed.jobs'
import { Route as AuthedFundingRouteImport } from './routes/_authed.funding'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedCustomersRouteImport } from './routes/_authed.customers'
import { Route as AuthedSubmissionsIdRouteImport } from './routes/_authed.submissions.$id'
import { Route as AuthedSettingsTeamRouteImport } from './routes/_authed.settings.team'
import { Route as AuthedSettingsSubscriptionRouteImport } from './routes/_authed.settings.subscription'
import { Route as AuthedSettingsSecurityRouteImport } from './routes/_authed.settings.security'
import { Route as AuthedSettingsProfileRouteImport } from './routes/_authed.settings.profile'
import { Route as AuthedSettingsNotificationsRouteImport } from './routes/_authed.settings.notifications'
import { Route as AuthedSettingsMeasuresRouteImport } from './routes/_authed.settings.measures'
import { Route as AuthedSettingsIntegrationsRouteImport } from './routes/_authed.settings.integrations'
import { Route as AuthedSettingsAccessRouteImport } from './routes/_authed.settings.access'
import { Route as AuthedPropertiesNewRouteImport } from './routes/_authed.properties.new'
import { Route as AuthedPropertiesIdRouteImport } from './routes/_authed.properties.$id'
import { Route as AuthedJobsNewRouteImport } from './routes/_authed.jobs.new'
import { Route as AuthedJobsIdRouteImport } from './routes/_authed.jobs.$id'
import { Route as AuthedIbgRepositoryRouteImport } from './routes/_authed.ibg.repository'
import { Route as AuthedIbgNewRouteImport } from './routes/_authed.ibg.new'
import { Route as AuthedIbgHistoryRouteImport } from './routes/_authed.ibg.history'
import { Route as AuthedIbgIdRouteImport } from './routes/_authed.ibg.$id'
import { Route as AuthedFundingMatchRouteImport } from './routes/_authed.funding.match'
import { Route as AuthedFundingIdRouteImport } from './routes/_authed.funding.$id'
import { Route as AuthedCustomersNewRouteImport } from './routes/_authed.customers.new'
import { Route as AuthedCustomersIdRouteImport } from './routes/_authed.customers.$id'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed.admin.users'
import { Route as AuthedAdminSystemSettingsRouteImport } from './routes/_authed.admin.system-settings'
import { Route as AuthedAdminStripeEventsRouteImport } from './routes/_authed.admin.stripe-events'
import { Route as AuthedAdminRiskOverridesRouteImport } from './routes/_authed.admin.risk-overrides'
import { Route as AuthedAdminRiskRouteImport } from './routes/_authed.admin.risk'
import { Route as AuthedAdminPermissionsRouteImport } from './routes/_authed.admin.permissions'
import { Route as AuthedAdminOnboardingRouteImport } from './routes/_authed.admin.onboarding'
import { Route as AuthedAdminMembershipRouteImport } from './routes/_authed.admin.membership'
import { Route as AuthedAdminMeasurePolicyRouteImport } from './routes/_authed.admin.measure-policy'
import { Route as AuthedAdminMeasureAccessRouteImport } from './routes/_authed.admin.measure-access'
import { Route as AuthedAdminIntegrationsRouteImport } from './routes/_authed.admin.integrations'
import { Route as AuthedAdminInstallationTypesRouteImport } from './routes/_authed.admin.installation-types'
import { Route as AuthedAdminFundingSchemesRouteImport } from './routes/_authed.admin.funding-schemes'
import { Route as AuthedAdminFeatureFlagsRouteImport } from './routes/_authed.admin.feature-flags'
import { Route as AuthedAdminExternalApisRouteImport } from './routes/_authed.admin.external-apis'
import { Route as AuthedAdminEvidenceRequirementsRouteImport } from './routes/_authed.admin.evidence-requirements'
import { Route as AuthedAdminCronRouteImport } from './routes/_authed.admin.cron'
import { Route as AuthedAdminCrmRouteImport } from './routes/_authed.admin.crm'
import { Route as AuthedAdminConfigRouteImport } from './routes/_authed.admin.config'
import { Route as AuthedAdminCompaniesRouteImport } from './routes/_authed.admin.companies'
import { Route as AuthedAdminAuditRouteImport } from './routes/_authed.admin.audit'
import { Route as AuthedAdminAmendmentsRouteImport } from './routes/_authed.admin.amendments'
import { Route as AuthedAdminActivityRouteImport } from './routes/_authed.admin.activity'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'
import { Route as AuthedIbgIdAmendmentRouteImport } from './routes/_authed.ibg.$id.amendment'
import { Route as AuthedFundingIdTrackingRouteImport } from './routes/_authed.funding.$id.tracking'
import { Route as AuthedAdminUsersIdRouteImport } from './routes/_authed.admin.users.$id'
import { Route as AuthedAdminStripeEventsIdRouteImport } from './routes/_authed.admin.stripe-events.$id'
import { Route as AuthedAdminRiskIdRouteImport } from './routes/_authed.admin.risk.$id'
import { Route as AuthedAdminOnboardingIdRouteImport } from './routes/_authed.admin.onboarding.$id'
import { Route as AuthedAdminIntegrationsIdRouteImport } from './routes/_authed.admin.integrations.$id'
import { Route as AuthedAdminCompaniesIdRouteImport } from './routes/_authed.admin.companies.$id'
import { Route as AuthedAdminAuditIdRouteImport } from './routes/_authed.admin.audit.$id'
import { Route as AuthedAdminAmendmentsIdRouteImport } from './routes/_authed.admin.amendments.$id'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSubmissionsRoute = AuthedSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPropertiesRoute = AuthedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsRoute = AuthedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsRoute = AuthedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFundingRoute = AuthedFundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomersRoute = AuthedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSubmissionsIdRoute = AuthedSubmissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedSubmissionsRoute,
} as any)
const AuthedSettingsTeamRoute = AuthedSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsSubscriptionRoute =
  AuthedSettingsSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsSecurityRoute = AuthedSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsProfileRoute = AuthedSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsNotificationsRoute =
  AuthedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsMeasuresRoute = AuthedSettingsMeasuresRouteImport.update({
  id: '/measures',
  path: '/measures',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsIntegrationsRoute =
  AuthedSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsAccessRoute = AuthedSettingsAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedPropertiesNewRoute = AuthedPropertiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedPropertiesRoute,
} as any)
const AuthedPropertiesIdRoute = AuthedPropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedPropertiesRoute,
} as any)
const AuthedJobsNewRoute = AuthedJobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedJobsRoute,
} as any)
const AuthedJobsIdRoute = AuthedJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedJobsRoute,
} as any)
const AuthedIbgRepositoryRoute = AuthedIbgRepositoryRouteImport.update({
  id: '/ibg/repository',
  path: '/ibg/repository',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIbgNewRoute = AuthedIbgNewRouteImport.update({
  id: '/ibg/new',
  path: '/ibg/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIbgHistoryRoute = AuthedIbgHistoryRouteImport.update({
  id: '/ibg/history',
  path: '/ibg/history',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIbgIdRoute = AuthedIbgIdRouteImport.update({
  id: '/ibg/$id',
  path: '/ibg/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFundingMatchRoute = AuthedFundingMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AuthedFundingRoute,
} as any)
const AuthedFundingIdRoute = AuthedFundingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedFundingRoute,
} as any)
const AuthedCustomersNewRoute = AuthedCustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedCustomersRoute,
} as any)
const AuthedCustomersIdRoute = AuthedCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedCustomersRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminSystemSettingsRoute =
  AuthedAdminSystemSettingsRouteImport.update({
    id: '/admin/system-settings',
    path: '/admin/system-settings',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminStripeEventsRoute = AuthedAdminStripeEventsRouteImport.update({
  id: '/admin/stripe-events',
  path: '/admin/stripe-events',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRiskOverridesRoute =
  AuthedAdminRiskOverridesRouteImport.update({
    id: '/admin/risk-overrides',
    path: '/admin/risk-overrides',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminRiskRoute = AuthedAdminRiskRouteImport.update({
  id: '/admin/risk',
  path: '/admin/risk',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminPermissionsRoute = AuthedAdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminOnboardingRoute = AuthedAdminOnboardingRouteImport.update({
  id: '/admin/onboarding',
  path: '/admin/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminMembershipRoute = AuthedAdminMembershipRouteImport.update({
  id: '/admin/membership',
  path: '/admin/membership',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminMeasurePolicyRoute =
  AuthedAdminMeasurePolicyRouteImport.update({
    id: '/admin/measure-policy',
    path: '/admin/measure-policy',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminMeasureAccessRoute =
  AuthedAdminMeasureAccessRouteImport.update({
    id: '/admin/measure-access',
    path: '/admin/measure-access',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminIntegrationsRoute = AuthedAdminIntegrationsRouteImport.update({
  id: '/admin/integrations',
  path: '/admin/integrations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminInstallationTypesRoute =
  AuthedAdminInstallationTypesRouteImport.update({
    id: '/admin/installation-types',
    path: '/admin/installation-types',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminFundingSchemesRoute =
  AuthedAdminFundingSchemesRouteImport.update({
    id: '/admin/funding-schemes',
    path: '/admin/funding-schemes',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminFeatureFlagsRoute = AuthedAdminFeatureFlagsRouteImport.update({
  id: '/admin/feature-flags',
  path: '/admin/feature-flags',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminExternalApisRoute = AuthedAdminExternalApisRouteImport.update({
  id: '/admin/external-apis',
  path: '/admin/external-apis',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminEvidenceRequirementsRoute =
  AuthedAdminEvidenceRequirementsRouteImport.update({
    id: '/admin/evidence-requirements',
    path: '/admin/evidence-requirements',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminCronRoute = AuthedAdminCronRouteImport.update({
  id: '/admin/cron',
  path: '/admin/cron',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminCrmRoute = AuthedAdminCrmRouteImport.update({
  id: '/admin/crm',
  path: '/admin/crm',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminConfigRoute = AuthedAdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminCompaniesRoute = AuthedAdminCompaniesRouteImport.update({
  id: '/admin/companies',
  path: '/admin/companies',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminAuditRoute = AuthedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminAmendmentsRoute = AuthedAdminAmendmentsRouteImport.update({
  id: '/admin/amendments',
  path: '/admin/amendments',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminActivityRoute = AuthedAdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIbgIdAmendmentRoute = AuthedIbgIdAmendmentRouteImport.update({
  id: '/amendment',
  path: '/amendment',
  getParentRoute: () => AuthedIbgIdRoute,
} as any)
const AuthedFundingIdTrackingRoute = AuthedFundingIdTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AuthedFundingIdRoute,
} as any)
const AuthedAdminUsersIdRoute = AuthedAdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedAdminUsersRoute,
} as any)
const AuthedAdminStripeEventsIdRoute =
  AuthedAdminStripeEventsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthedAdminStripeEventsRoute,
  } as any)
const AuthedAdminRiskIdRoute = AuthedAdminRiskIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedAdminRiskRoute,
} as any)
const AuthedAdminOnboardingIdRoute = AuthedAdminOnboardingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedAdminOnboardingRoute,
} as any)
const AuthedAdminIntegrationsIdRoute =
  AuthedAdminIntegrationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthedAdminIntegrationsRoute,
  } as any)
const AuthedAdminCompaniesIdRoute = AuthedAdminCompaniesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedAdminCompaniesRoute,
} as any)
const AuthedAdminAuditIdRoute = AuthedAdminAuditIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedAdminAuditRoute,
} as any)
const AuthedAdminAmendmentsIdRoute = AuthedAdminAmendmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedAdminAmendmentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify': typeof VerifyRoute
  '/customers': typeof AuthedCustomersRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/funding': typeof AuthedFundingRouteWithChildren
  '/jobs': typeof AuthedJobsRouteWithChildren
  '/onboarding': typeof AuthedOnboardingRoute
  '/projects': typeof AuthedProjectsRoute
  '/properties': typeof AuthedPropertiesRouteWithChildren
  '/reports': typeof AuthedReportsRoute
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/submissions': typeof AuthedSubmissionsRouteWithChildren
  '/admin/activity': typeof AuthedAdminActivityRoute
  '/admin/amendments': typeof AuthedAdminAmendmentsRouteWithChildren
  '/admin/audit': typeof AuthedAdminAuditRouteWithChildren
  '/admin/companies': typeof AuthedAdminCompaniesRouteWithChildren
  '/admin/config': typeof AuthedAdminConfigRoute
  '/admin/crm': typeof AuthedAdminCrmRoute
  '/admin/cron': typeof AuthedAdminCronRoute
  '/admin/evidence-requirements': typeof AuthedAdminEvidenceRequirementsRoute
  '/admin/external-apis': typeof AuthedAdminExternalApisRoute
  '/admin/feature-flags': typeof AuthedAdminFeatureFlagsRoute
  '/admin/funding-schemes': typeof AuthedAdminFundingSchemesRoute
  '/admin/installation-types': typeof AuthedAdminInstallationTypesRoute
  '/admin/integrations': typeof AuthedAdminIntegrationsRouteWithChildren
  '/admin/measure-access': typeof AuthedAdminMeasureAccessRoute
  '/admin/measure-policy': typeof AuthedAdminMeasurePolicyRoute
  '/admin/membership': typeof AuthedAdminMembershipRoute
  '/admin/onboarding': typeof AuthedAdminOnboardingRouteWithChildren
  '/admin/permissions': typeof AuthedAdminPermissionsRoute
  '/admin/risk': typeof AuthedAdminRiskRouteWithChildren
  '/admin/risk-overrides': typeof AuthedAdminRiskOverridesRoute
  '/admin/stripe-events': typeof AuthedAdminStripeEventsRouteWithChildren
  '/admin/system-settings': typeof AuthedAdminSystemSettingsRoute
  '/admin/users': typeof AuthedAdminUsersRouteWithChildren
  '/customers/$id': typeof AuthedCustomersIdRoute
  '/customers/new': typeof AuthedCustomersNewRoute
  '/funding/$id': typeof AuthedFundingIdRouteWithChildren
  '/funding/match': typeof AuthedFundingMatchRoute
  '/ibg/$id': typeof AuthedIbgIdRouteWithChildren
  '/ibg/history': typeof AuthedIbgHistoryRoute
  '/ibg/new': typeof AuthedIbgNewRoute
  '/ibg/repository': typeof AuthedIbgRepositoryRoute
  '/jobs/$id': typeof AuthedJobsIdRoute
  '/jobs/new': typeof AuthedJobsNewRoute
  '/properties/$id': typeof AuthedPropertiesIdRoute
  '/properties/new': typeof AuthedPropertiesNewRoute
  '/settings/access': typeof AuthedSettingsAccessRoute
  '/settings/integrations': typeof AuthedSettingsIntegrationsRoute
  '/settings/measures': typeof AuthedSettingsMeasuresRoute
  '/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
  '/settings/security': typeof AuthedSettingsSecurityRoute
  '/settings/subscription': typeof AuthedSettingsSubscriptionRoute
  '/settings/team': typeof AuthedSettingsTeamRoute
  '/submissions/$id': typeof AuthedSubmissionsIdRoute
  '/admin/amendments/$id': typeof AuthedAdminAmendmentsIdRoute
  '/admin/audit/$id': typeof AuthedAdminAuditIdRoute
  '/admin/companies/$id': typeof AuthedAdminCompaniesIdRoute
  '/admin/integrations/$id': typeof AuthedAdminIntegrationsIdRoute
  '/admin/onboarding/$id': typeof AuthedAdminOnboardingIdRoute
  '/admin/risk/$id': typeof AuthedAdminRiskIdRoute
  '/admin/stripe-events/$id': typeof AuthedAdminStripeEventsIdRoute
  '/admin/users/$id': typeof AuthedAdminUsersIdRoute
  '/funding/$id/tracking': typeof AuthedFundingIdTrackingRoute
  '/ibg/$id/amendment': typeof AuthedIbgIdAmendmentRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify': typeof VerifyRoute
  '/customers': typeof AuthedCustomersRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/funding': typeof AuthedFundingRouteWithChildren
  '/jobs': typeof AuthedJobsRouteWithChildren
  '/onboarding': typeof AuthedOnboardingRoute
  '/projects': typeof AuthedProjectsRoute
  '/properties': typeof AuthedPropertiesRouteWithChildren
  '/reports': typeof AuthedReportsRoute
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/submissions': typeof AuthedSubmissionsRouteWithChildren
  '/admin/activity': typeof AuthedAdminActivityRoute
  '/admin/amendments': typeof AuthedAdminAmendmentsRouteWithChildren
  '/admin/audit': typeof AuthedAdminAuditRouteWithChildren
  '/admin/companies': typeof AuthedAdminCompaniesRouteWithChildren
  '/admin/config': typeof AuthedAdminConfigRoute
  '/admin/crm': typeof AuthedAdminCrmRoute
  '/admin/cron': typeof AuthedAdminCronRoute
  '/admin/evidence-requirements': typeof AuthedAdminEvidenceRequirementsRoute
  '/admin/external-apis': typeof AuthedAdminExternalApisRoute
  '/admin/feature-flags': typeof AuthedAdminFeatureFlagsRoute
  '/admin/funding-schemes': typeof AuthedAdminFundingSchemesRoute
  '/admin/installation-types': typeof AuthedAdminInstallationTypesRoute
  '/admin/integrations': typeof AuthedAdminIntegrationsRouteWithChildren
  '/admin/measure-access': typeof AuthedAdminMeasureAccessRoute
  '/admin/measure-policy': typeof AuthedAdminMeasurePolicyRoute
  '/admin/membership': typeof AuthedAdminMembershipRoute
  '/admin/onboarding': typeof AuthedAdminOnboardingRouteWithChildren
  '/admin/permissions': typeof AuthedAdminPermissionsRoute
  '/admin/risk': typeof AuthedAdminRiskRouteWithChildren
  '/admin/risk-overrides': typeof AuthedAdminRiskOverridesRoute
  '/admin/stripe-events': typeof AuthedAdminStripeEventsRouteWithChildren
  '/admin/system-settings': typeof AuthedAdminSystemSettingsRoute
  '/admin/users': typeof AuthedAdminUsersRouteWithChildren
  '/customers/$id': typeof AuthedCustomersIdRoute
  '/customers/new': typeof AuthedCustomersNewRoute
  '/funding/$id': typeof AuthedFundingIdRouteWithChildren
  '/funding/match': typeof AuthedFundingMatchRoute
  '/ibg/$id': typeof AuthedIbgIdRouteWithChildren
  '/ibg/history': typeof AuthedIbgHistoryRoute
  '/ibg/new': typeof AuthedIbgNewRoute
  '/ibg/repository': typeof AuthedIbgRepositoryRoute
  '/jobs/$id': typeof AuthedJobsIdRoute
  '/jobs/new': typeof AuthedJobsNewRoute
  '/properties/$id': typeof AuthedPropertiesIdRoute
  '/properties/new': typeof AuthedPropertiesNewRoute
  '/settings/access': typeof AuthedSettingsAccessRoute
  '/settings/integrations': typeof AuthedSettingsIntegrationsRoute
  '/settings/measures': typeof AuthedSettingsMeasuresRoute
  '/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
  '/settings/security': typeof AuthedSettingsSecurityRoute
  '/settings/subscription': typeof AuthedSettingsSubscriptionRoute
  '/settings/team': typeof AuthedSettingsTeamRoute
  '/submissions/$id': typeof AuthedSubmissionsIdRoute
  '/admin/amendments/$id': typeof AuthedAdminAmendmentsIdRoute
  '/admin/audit/$id': typeof AuthedAdminAuditIdRoute
  '/admin/companies/$id': typeof AuthedAdminCompaniesIdRoute
  '/admin/integrations/$id': typeof AuthedAdminIntegrationsIdRoute
  '/admin/onboarding/$id': typeof AuthedAdminOnboardingIdRoute
  '/admin/risk/$id': typeof AuthedAdminRiskIdRoute
  '/admin/stripe-events/$id': typeof AuthedAdminStripeEventsIdRoute
  '/admin/users/$id': typeof AuthedAdminUsersIdRoute
  '/funding/$id/tracking': typeof AuthedFundingIdTrackingRoute
  '/ibg/$id/amendment': typeof AuthedIbgIdAmendmentRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify': typeof VerifyRoute
  '/_authed/customers': typeof AuthedCustomersRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/funding': typeof AuthedFundingRouteWithChildren
  '/_authed/jobs': typeof AuthedJobsRouteWithChildren
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_authed/projects': typeof AuthedProjectsRoute
  '/_authed/properties': typeof AuthedPropertiesRouteWithChildren
  '/_authed/reports': typeof AuthedReportsRoute
  '/_authed/settings': typeof AuthedSettingsRouteWithChildren
  '/_authed/submissions': typeof AuthedSubmissionsRouteWithChildren
  '/_authed/admin/activity': typeof AuthedAdminActivityRoute
  '/_authed/admin/amendments': typeof AuthedAdminAmendmentsRouteWithChildren
  '/_authed/admin/audit': typeof AuthedAdminAuditRouteWithChildren
  '/_authed/admin/companies': typeof AuthedAdminCompaniesRouteWithChildren
  '/_authed/admin/config': typeof AuthedAdminConfigRoute
  '/_authed/admin/crm': typeof AuthedAdminCrmRoute
  '/_authed/admin/cron': typeof AuthedAdminCronRoute
  '/_authed/admin/evidence-requirements': typeof AuthedAdminEvidenceRequirementsRoute
  '/_authed/admin/external-apis': typeof AuthedAdminExternalApisRoute
  '/_authed/admin/feature-flags': typeof AuthedAdminFeatureFlagsRoute
  '/_authed/admin/funding-schemes': typeof AuthedAdminFundingSchemesRoute
  '/_authed/admin/installation-types': typeof AuthedAdminInstallationTypesRoute
  '/_authed/admin/integrations': typeof AuthedAdminIntegrationsRouteWithChildren
  '/_authed/admin/measure-access': typeof AuthedAdminMeasureAccessRoute
  '/_authed/admin/measure-policy': typeof AuthedAdminMeasurePolicyRoute
  '/_authed/admin/membership': typeof AuthedAdminMembershipRoute
  '/_authed/admin/onboarding': typeof AuthedAdminOnboardingRouteWithChildren
  '/_authed/admin/permissions': typeof AuthedAdminPermissionsRoute
  '/_authed/admin/risk': typeof AuthedAdminRiskRouteWithChildren
  '/_authed/admin/risk-overrides': typeof AuthedAdminRiskOverridesRoute
  '/_authed/admin/stripe-events': typeof AuthedAdminStripeEventsRouteWithChildren
  '/_authed/admin/system-settings': typeof AuthedAdminSystemSettingsRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRouteWithChildren
  '/_authed/customers/$id': typeof AuthedCustomersIdRoute
  '/_authed/customers/new': typeof AuthedCustomersNewRoute
  '/_authed/funding/$id': typeof AuthedFundingIdRouteWithChildren
  '/_authed/funding/match': typeof AuthedFundingMatchRoute
  '/_authed/ibg/$id': typeof AuthedIbgIdRouteWithChildren
  '/_authed/ibg/history': typeof AuthedIbgHistoryRoute
  '/_authed/ibg/new': typeof AuthedIbgNewRoute
  '/_authed/ibg/repository': typeof AuthedIbgRepositoryRoute
  '/_authed/jobs/$id': typeof AuthedJobsIdRoute
  '/_authed/jobs/new': typeof AuthedJobsNewRoute
  '/_authed/properties/$id': typeof AuthedPropertiesIdRoute
  '/_authed/properties/new': typeof AuthedPropertiesNewRoute
  '/_authed/settings/access': typeof AuthedSettingsAccessRoute
  '/_authed/settings/integrations': typeof AuthedSettingsIntegrationsRoute
  '/_authed/settings/measures': typeof AuthedSettingsMeasuresRoute
  '/_authed/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/_authed/settings/profile': typeof AuthedSettingsProfileRoute
  '/_authed/settings/security': typeof AuthedSettingsSecurityRoute
  '/_authed/settings/subscription': typeof AuthedSettingsSubscriptionRoute
  '/_authed/settings/team': typeof AuthedSettingsTeamRoute
  '/_authed/submissions/$id': typeof AuthedSubmissionsIdRoute
  '/_authed/admin/amendments/$id': typeof AuthedAdminAmendmentsIdRoute
  '/_authed/admin/audit/$id': typeof AuthedAdminAuditIdRoute
  '/_authed/admin/companies/$id': typeof AuthedAdminCompaniesIdRoute
  '/_authed/admin/integrations/$id': typeof AuthedAdminIntegrationsIdRoute
  '/_authed/admin/onboarding/$id': typeof AuthedAdminOnboardingIdRoute
  '/_authed/admin/risk/$id': typeof AuthedAdminRiskIdRoute
  '/_authed/admin/stripe-events/$id': typeof AuthedAdminStripeEventsIdRoute
  '/_authed/admin/users/$id': typeof AuthedAdminUsersIdRoute
  '/_authed/funding/$id/tracking': typeof AuthedFundingIdTrackingRoute
  '/_authed/ibg/$id/amendment': typeof AuthedIbgIdAmendmentRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/pricing'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify'
    | '/customers'
    | '/dashboard'
    | '/funding'
    | '/jobs'
    | '/onboarding'
    | '/projects'
    | '/properties'
    | '/reports'
    | '/settings'
    | '/submissions'
    | '/admin/activity'
    | '/admin/amendments'
    | '/admin/audit'
    | '/admin/companies'
    | '/admin/config'
    | '/admin/crm'
    | '/admin/cron'
    | '/admin/evidence-requirements'
    | '/admin/external-apis'
    | '/admin/feature-flags'
    | '/admin/funding-schemes'
    | '/admin/installation-types'
    | '/admin/integrations'
    | '/admin/measure-access'
    | '/admin/measure-policy'
    | '/admin/membership'
    | '/admin/onboarding'
    | '/admin/permissions'
    | '/admin/risk'
    | '/admin/risk-overrides'
    | '/admin/stripe-events'
    | '/admin/system-settings'
    | '/admin/users'
    | '/customers/$id'
    | '/customers/new'
    | '/funding/$id'
    | '/funding/match'
    | '/ibg/$id'
    | '/ibg/history'
    | '/ibg/new'
    | '/ibg/repository'
    | '/jobs/$id'
    | '/jobs/new'
    | '/properties/$id'
    | '/properties/new'
    | '/settings/access'
    | '/settings/integrations'
    | '/settings/measures'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/subscription'
    | '/settings/team'
    | '/submissions/$id'
    | '/admin/amendments/$id'
    | '/admin/audit/$id'
    | '/admin/companies/$id'
    | '/admin/integrations/$id'
    | '/admin/onboarding/$id'
    | '/admin/risk/$id'
    | '/admin/stripe-events/$id'
    | '/admin/users/$id'
    | '/funding/$id/tracking'
    | '/ibg/$id/amendment'
    | '/api/public/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/pricing'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify'
    | '/customers'
    | '/dashboard'
    | '/funding'
    | '/jobs'
    | '/onboarding'
    | '/projects'
    | '/properties'
    | '/reports'
    | '/settings'
    | '/submissions'
    | '/admin/activity'
    | '/admin/amendments'
    | '/admin/audit'
    | '/admin/companies'
    | '/admin/config'
    | '/admin/crm'
    | '/admin/cron'
    | '/admin/evidence-requirements'
    | '/admin/external-apis'
    | '/admin/feature-flags'
    | '/admin/funding-schemes'
    | '/admin/installation-types'
    | '/admin/integrations'
    | '/admin/measure-access'
    | '/admin/measure-policy'
    | '/admin/membership'
    | '/admin/onboarding'
    | '/admin/permissions'
    | '/admin/risk'
    | '/admin/risk-overrides'
    | '/admin/stripe-events'
    | '/admin/system-settings'
    | '/admin/users'
    | '/customers/$id'
    | '/customers/new'
    | '/funding/$id'
    | '/funding/match'
    | '/ibg/$id'
    | '/ibg/history'
    | '/ibg/new'
    | '/ibg/repository'
    | '/jobs/$id'
    | '/jobs/new'
    | '/properties/$id'
    | '/properties/new'
    | '/settings/access'
    | '/settings/integrations'
    | '/settings/measures'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/subscription'
    | '/settings/team'
    | '/submissions/$id'
    | '/admin/amendments/$id'
    | '/admin/audit/$id'
    | '/admin/companies/$id'
    | '/admin/integrations/$id'
    | '/admin/onboarding/$id'
    | '/admin/risk/$id'
    | '/admin/stripe-events/$id'
    | '/admin/users/$id'
    | '/funding/$id/tracking'
    | '/ibg/$id/amendment'
    | '/api/public/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/pricing'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify'
    | '/_authed/customers'
    | '/_authed/dashboard'
    | '/_authed/funding'
    | '/_authed/jobs'
    | '/_authed/onboarding'
    | '/_authed/projects'
    | '/_authed/properties'
    | '/_authed/reports'
    | '/_authed/settings'
    | '/_authed/submissions'
    | '/_authed/admin/activity'
    | '/_authed/admin/amendments'
    | '/_authed/admin/audit'
    | '/_authed/admin/companies'
    | '/_authed/admin/config'
    | '/_authed/admin/crm'
    | '/_authed/admin/cron'
    | '/_authed/admin/evidence-requirements'
    | '/_authed/admin/external-apis'
    | '/_authed/admin/feature-flags'
    | '/_authed/admin/funding-schemes'
    | '/_authed/admin/installation-types'
    | '/_authed/admin/integrations'
    | '/_authed/admin/measure-access'
    | '/_authed/admin/measure-policy'
    | '/_authed/admin/membership'
    | '/_authed/admin/onboarding'
    | '/_authed/admin/permissions'
    | '/_authed/admin/risk'
    | '/_authed/admin/risk-overrides'
    | '/_authed/admin/stripe-events'
    | '/_authed/admin/system-settings'
    | '/_authed/admin/users'
    | '/_authed/customers/$id'
    | '/_authed/customers/new'
    | '/_authed/funding/$id'
    | '/_authed/funding/match'
    | '/_authed/ibg/$id'
    | '/_authed/ibg/history'
    | '/_authed/ibg/new'
    | '/_authed/ibg/repository'
    | '/_authed/jobs/$id'
    | '/_authed/jobs/new'
    | '/_authed/properties/$id'
    | '/_authed/properties/new'
    | '/_authed/settings/access'
    | '/_authed/settings/integrations'
    | '/_authed/settings/measures'
    | '/_authed/settings/notifications'
    | '/_authed/settings/profile'
    | '/_authed/settings/security'
    | '/_authed/settings/subscription'
    | '/_authed/settings/team'
    | '/_authed/submissions/$id'
    | '/_authed/admin/amendments/$id'
    | '/_authed/admin/audit/$id'
    | '/_authed/admin/companies/$id'
    | '/_authed/admin/integrations/$id'
    | '/_authed/admin/onboarding/$id'
    | '/_authed/admin/risk/$id'
    | '/_authed/admin/stripe-events/$id'
    | '/_authed/admin/users/$id'
    | '/_authed/funding/$id/tracking'
    | '/_authed/ibg/$id/amendment'
    | '/api/public/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  VerifyRoute: typeof VerifyRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/submissions': {
      id: '/_authed/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthedSubmissionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/properties': {
      id: '/_authed/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthedPropertiesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects': {
      id: '/_authed/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthedProjectsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs': {
      id: '/_authed/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthedJobsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/funding': {
      id: '/_authed/funding'
      path: '/funding'
      fullPath: '/funding'
      preLoaderRoute: typeof AuthedFundingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers': {
      id: '/_authed/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthedCustomersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/submissions/$id': {
      id: '/_authed/submissions/$id'
      path: '/$id'
      fullPath: '/submissions/$id'
      preLoaderRoute: typeof AuthedSubmissionsIdRouteImport
      parentRoute: typeof AuthedSubmissionsRoute
    }
    '/_authed/settings/team': {
      id: '/_authed/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthedSettingsTeamRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/subscription': {
      id: '/_authed/settings/subscription'
      path: '/subscription'
      fullPath: '/settings/subscription'
      preLoaderRoute: typeof AuthedSettingsSubscriptionRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/security': {
      id: '/_authed/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthedSettingsSecurityRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/profile': {
      id: '/_authed/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthedSettingsProfileRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/notifications': {
      id: '/_authed/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthedSettingsNotificationsRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/measures': {
      id: '/_authed/settings/measures'
      path: '/measures'
      fullPath: '/settings/measures'
      preLoaderRoute: typeof AuthedSettingsMeasuresRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/integrations': {
      id: '/_authed/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/access': {
      id: '/_authed/settings/access'
      path: '/access'
      fullPath: '/settings/access'
      preLoaderRoute: typeof AuthedSettingsAccessRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/properties/new': {
      id: '/_authed/properties/new'
      path: '/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof AuthedPropertiesNewRouteImport
      parentRoute: typeof AuthedPropertiesRoute
    }
    '/_authed/properties/$id': {
      id: '/_authed/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof AuthedPropertiesIdRouteImport
      parentRoute: typeof AuthedPropertiesRoute
    }
    '/_authed/jobs/new': {
      id: '/_authed/jobs/new'
      path: '/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AuthedJobsNewRouteImport
      parentRoute: typeof AuthedJobsRoute
    }
    '/_authed/jobs/$id': {
      id: '/_authed/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AuthedJobsIdRouteImport
      parentRoute: typeof AuthedJobsRoute
    }
    '/_authed/ibg/repository': {
      id: '/_authed/ibg/repository'
      path: '/ibg/repository'
      fullPath: '/ibg/repository'
      preLoaderRoute: typeof AuthedIbgRepositoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ibg/new': {
      id: '/_authed/ibg/new'
      path: '/ibg/new'
      fullPath: '/ibg/new'
      preLoaderRoute: typeof AuthedIbgNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ibg/history': {
      id: '/_authed/ibg/history'
      path: '/ibg/history'
      fullPath: '/ibg/history'
      preLoaderRoute: typeof AuthedIbgHistoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ibg/$id': {
      id: '/_authed/ibg/$id'
      path: '/ibg/$id'
      fullPath: '/ibg/$id'
      preLoaderRoute: typeof AuthedIbgIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/funding/match': {
      id: '/_authed/funding/match'
      path: '/match'
      fullPath: '/funding/match'
      preLoaderRoute: typeof AuthedFundingMatchRouteImport
      parentRoute: typeof AuthedFundingRoute
    }
    '/_authed/funding/$id': {
      id: '/_authed/funding/$id'
      path: '/$id'
      fullPath: '/funding/$id'
      preLoaderRoute: typeof AuthedFundingIdRouteImport
      parentRoute: typeof AuthedFundingRoute
    }
    '/_authed/customers/new': {
      id: '/_authed/customers/new'
      path: '/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AuthedCustomersNewRouteImport
      parentRoute: typeof AuthedCustomersRoute
    }
    '/_authed/customers/$id': {
      id: '/_authed/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthedCustomersIdRouteImport
      parentRoute: typeof AuthedCustomersRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/system-settings': {
      id: '/_authed/admin/system-settings'
      path: '/admin/system-settings'
      fullPath: '/admin/system-settings'
      preLoaderRoute: typeof AuthedAdminSystemSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/stripe-events': {
      id: '/_authed/admin/stripe-events'
      path: '/admin/stripe-events'
      fullPath: '/admin/stripe-events'
      preLoaderRoute: typeof AuthedAdminStripeEventsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/risk-overrides': {
      id: '/_authed/admin/risk-overrides'
      path: '/admin/risk-overrides'
      fullPath: '/admin/risk-overrides'
      preLoaderRoute: typeof AuthedAdminRiskOverridesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/risk': {
      id: '/_authed/admin/risk'
      path: '/admin/risk'
      fullPath: '/admin/risk'
      preLoaderRoute: typeof AuthedAdminRiskRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/permissions': {
      id: '/_authed/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthedAdminPermissionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/onboarding': {
      id: '/_authed/admin/onboarding'
      path: '/admin/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AuthedAdminOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/membership': {
      id: '/_authed/admin/membership'
      path: '/admin/membership'
      fullPath: '/admin/membership'
      preLoaderRoute: typeof AuthedAdminMembershipRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/measure-policy': {
      id: '/_authed/admin/measure-policy'
      path: '/admin/measure-policy'
      fullPath: '/admin/measure-policy'
      preLoaderRoute: typeof AuthedAdminMeasurePolicyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/measure-access': {
      id: '/_authed/admin/measure-access'
      path: '/admin/measure-access'
      fullPath: '/admin/measure-access'
      preLoaderRoute: typeof AuthedAdminMeasureAccessRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/integrations': {
      id: '/_authed/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthedAdminIntegrationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/installation-types': {
      id: '/_authed/admin/installation-types'
      path: '/admin/installation-types'
      fullPath: '/admin/installation-types'
      preLoaderRoute: typeof AuthedAdminInstallationTypesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/funding-schemes': {
      id: '/_authed/admin/funding-schemes'
      path: '/admin/funding-schemes'
      fullPath: '/admin/funding-schemes'
      preLoaderRoute: typeof AuthedAdminFundingSchemesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/feature-flags': {
      id: '/_authed/admin/feature-flags'
      path: '/admin/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof AuthedAdminFeatureFlagsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/external-apis': {
      id: '/_authed/admin/external-apis'
      path: '/admin/external-apis'
      fullPath: '/admin/external-apis'
      preLoaderRoute: typeof AuthedAdminExternalApisRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/evidence-requirements': {
      id: '/_authed/admin/evidence-requirements'
      path: '/admin/evidence-requirements'
      fullPath: '/admin/evidence-requirements'
      preLoaderRoute: typeof AuthedAdminEvidenceRequirementsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/cron': {
      id: '/_authed/admin/cron'
      path: '/admin/cron'
      fullPath: '/admin/cron'
      preLoaderRoute: typeof AuthedAdminCronRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/crm': {
      id: '/_authed/admin/crm'
      path: '/admin/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AuthedAdminCrmRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/config': {
      id: '/_authed/admin/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AuthedAdminConfigRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/companies': {
      id: '/_authed/admin/companies'
      path: '/admin/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AuthedAdminCompaniesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/audit': {
      id: '/_authed/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthedAdminAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/amendments': {
      id: '/_authed/admin/amendments'
      path: '/admin/amendments'
      fullPath: '/admin/amendments'
      preLoaderRoute: typeof AuthedAdminAmendmentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/activity': {
      id: '/_authed/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthedAdminActivityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/ibg/$id/amendment': {
      id: '/_authed/ibg/$id/amendment'
      path: '/amendment'
      fullPath: '/ibg/$id/amendment'
      preLoaderRoute: typeof AuthedIbgIdAmendmentRouteImport
      parentRoute: typeof AuthedIbgIdRoute
    }
    '/_authed/funding/$id/tracking': {
      id: '/_authed/funding/$id/tracking'
      path: '/tracking'
      fullPath: '/funding/$id/tracking'
      preLoaderRoute: typeof AuthedFundingIdTrackingRouteImport
      parentRoute: typeof AuthedFundingIdRoute
    }
    '/_authed/admin/users/$id': {
      id: '/_authed/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthedAdminUsersIdRouteImport
      parentRoute: typeof AuthedAdminUsersRoute
    }
    '/_authed/admin/stripe-events/$id': {
      id: '/_authed/admin/stripe-events/$id'
      path: '/$id'
      fullPath: '/admin/stripe-events/$id'
      preLoaderRoute: typeof AuthedAdminStripeEventsIdRouteImport
      parentRoute: typeof AuthedAdminStripeEventsRoute
    }
    '/_authed/admin/risk/$id': {
      id: '/_authed/admin/risk/$id'
      path: '/$id'
      fullPath: '/admin/risk/$id'
      preLoaderRoute: typeof AuthedAdminRiskIdRouteImport
      parentRoute: typeof AuthedAdminRiskRoute
    }
    '/_authed/admin/onboarding/$id': {
      id: '/_authed/admin/onboarding/$id'
      path: '/$id'
      fullPath: '/admin/onboarding/$id'
      preLoaderRoute: typeof AuthedAdminOnboardingIdRouteImport
      parentRoute: typeof AuthedAdminOnboardingRoute
    }
    '/_authed/admin/integrations/$id': {
      id: '/_authed/admin/integrations/$id'
      path: '/$id'
      fullPath: '/admin/integrations/$id'
      preLoaderRoute: typeof AuthedAdminIntegrationsIdRouteImport
      parentRoute: typeof AuthedAdminIntegrationsRoute
    }
    '/_authed/admin/companies/$id': {
      id: '/_authed/admin/companies/$id'
      path: '/$id'
      fullPath: '/admin/companies/$id'
      preLoaderRoute: typeof AuthedAdminCompaniesIdRouteImport
      parentRoute: typeof AuthedAdminCompaniesRoute
    }
    '/_authed/admin/audit/$id': {
      id: '/_authed/admin/audit/$id'
      path: '/$id'
      fullPath: '/admin/audit/$id'
      preLoaderRoute: typeof AuthedAdminAuditIdRouteImport
      parentRoute: typeof AuthedAdminAuditRoute
    }
    '/_authed/admin/amendments/$id': {
      id: '/_authed/admin/amendments/$id'
      path: '/$id'
      fullPath: '/admin/amendments/$id'
      preLoaderRoute: typeof AuthedAdminAmendmentsIdRouteImport
      parentRoute: typeof AuthedAdminAmendmentsRoute
    }
  }
}

interface AuthedCustomersRouteChildren {
  AuthedCustomersIdRoute: typeof AuthedCustomersIdRoute
  AuthedCustomersNewRoute: typeof AuthedCustomersNewRoute
}

const AuthedCustomersRouteChildren: AuthedCustomersRouteChildren = {
  AuthedCustomersIdRoute: AuthedCustomersIdRoute,
  AuthedCustomersNewRoute: AuthedCustomersNewRoute,
}

const AuthedCustomersRouteWithChildren = AuthedCustomersRoute._addFileChildren(
  AuthedCustomersRouteChildren,
)

interface AuthedFundingIdRouteChildren {
  AuthedFundingIdTrackingRoute: typeof AuthedFundingIdTrackingRoute
}

const AuthedFundingIdRouteChildren: AuthedFundingIdRouteChildren = {
  AuthedFundingIdTrackingRoute: AuthedFundingIdTrackingRoute,
}

const AuthedFundingIdRouteWithChildren = AuthedFundingIdRoute._addFileChildren(
  AuthedFundingIdRouteChildren,
)

interface AuthedFundingRouteChildren {
  AuthedFundingIdRoute: typeof AuthedFundingIdRouteWithChildren
  AuthedFundingMatchRoute: typeof AuthedFundingMatchRoute
}

const AuthedFundingRouteChildren: AuthedFundingRouteChildren = {
  AuthedFundingIdRoute: AuthedFundingIdRouteWithChildren,
  AuthedFundingMatchRoute: AuthedFundingMatchRoute,
}

const AuthedFundingRouteWithChildren = AuthedFundingRoute._addFileChildren(
  AuthedFundingRouteChildren,
)

interface AuthedJobsRouteChildren {
  AuthedJobsIdRoute: typeof AuthedJobsIdRoute
  AuthedJobsNewRoute: typeof AuthedJobsNewRoute
}

const AuthedJobsRouteChildren: AuthedJobsRouteChildren = {
  AuthedJobsIdRoute: AuthedJobsIdRoute,
  AuthedJobsNewRoute: AuthedJobsNewRoute,
}

const AuthedJobsRouteWithChildren = AuthedJobsRoute._addFileChildren(
  AuthedJobsRouteChildren,
)

interface AuthedPropertiesRouteChildren {
  AuthedPropertiesIdRoute: typeof AuthedPropertiesIdRoute
  AuthedPropertiesNewRoute: typeof AuthedPropertiesNewRoute
}

const AuthedPropertiesRouteChildren: AuthedPropertiesRouteChildren = {
  AuthedPropertiesIdRoute: AuthedPropertiesIdRoute,
  AuthedPropertiesNewRoute: AuthedPropertiesNewRoute,
}

const AuthedPropertiesRouteWithChildren =
  AuthedPropertiesRoute._addFileChildren(AuthedPropertiesRouteChildren)

interface AuthedSettingsRouteChildren {
  AuthedSettingsAccessRoute: typeof AuthedSettingsAccessRoute
  AuthedSettingsIntegrationsRoute: typeof AuthedSettingsIntegrationsRoute
  AuthedSettingsMeasuresRoute: typeof AuthedSettingsMeasuresRoute
  AuthedSettingsNotificationsRoute: typeof AuthedSettingsNotificationsRoute
  AuthedSettingsProfileRoute: typeof AuthedSettingsProfileRoute
  AuthedSettingsSecurityRoute: typeof AuthedSettingsSecurityRoute
  AuthedSettingsSubscriptionRoute: typeof AuthedSettingsSubscriptionRoute
  AuthedSettingsTeamRoute: typeof AuthedSettingsTeamRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsAccessRoute: AuthedSettingsAccessRoute,
  AuthedSettingsIntegrationsRoute: AuthedSettingsIntegrationsRoute,
  AuthedSettingsMeasuresRoute: AuthedSettingsMeasuresRoute,
  AuthedSettingsNotificationsRoute: AuthedSettingsNotificationsRoute,
  AuthedSettingsProfileRoute: AuthedSettingsProfileRoute,
  AuthedSettingsSecurityRoute: AuthedSettingsSecurityRoute,
  AuthedSettingsSubscriptionRoute: AuthedSettingsSubscriptionRoute,
  AuthedSettingsTeamRoute: AuthedSettingsTeamRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedSubmissionsRouteChildren {
  AuthedSubmissionsIdRoute: typeof AuthedSubmissionsIdRoute
}

const AuthedSubmissionsRouteChildren: AuthedSubmissionsRouteChildren = {
  AuthedSubmissionsIdRoute: AuthedSubmissionsIdRoute,
}

const AuthedSubmissionsRouteWithChildren =
  AuthedSubmissionsRoute._addFileChildren(AuthedSubmissionsRouteChildren)

interface AuthedAdminAmendmentsRouteChildren {
  AuthedAdminAmendmentsIdRoute: typeof AuthedAdminAmendmentsIdRoute
}

const AuthedAdminAmendmentsRouteChildren: AuthedAdminAmendmentsRouteChildren = {
  AuthedAdminAmendmentsIdRoute: AuthedAdminAmendmentsIdRoute,
}

const AuthedAdminAmendmentsRouteWithChildren =
  AuthedAdminAmendmentsRoute._addFileChildren(
    AuthedAdminAmendmentsRouteChildren,
  )

interface AuthedAdminAuditRouteChildren {
  AuthedAdminAuditIdRoute: typeof AuthedAdminAuditIdRoute
}

const AuthedAdminAuditRouteChildren: AuthedAdminAuditRouteChildren = {
  AuthedAdminAuditIdRoute: AuthedAdminAuditIdRoute,
}

const AuthedAdminAuditRouteWithChildren =
  AuthedAdminAuditRoute._addFileChildren(AuthedAdminAuditRouteChildren)

interface AuthedAdminCompaniesRouteChildren {
  AuthedAdminCompaniesIdRoute: typeof AuthedAdminCompaniesIdRoute
}

const AuthedAdminCompaniesRouteChildren: AuthedAdminCompaniesRouteChildren = {
  AuthedAdminCompaniesIdRoute: AuthedAdminCompaniesIdRoute,
}

const AuthedAdminCompaniesRouteWithChildren =
  AuthedAdminCompaniesRoute._addFileChildren(AuthedAdminCompaniesRouteChildren)

interface AuthedAdminIntegrationsRouteChildren {
  AuthedAdminIntegrationsIdRoute: typeof AuthedAdminIntegrationsIdRoute
}

const AuthedAdminIntegrationsRouteChildren: AuthedAdminIntegrationsRouteChildren =
  {
    AuthedAdminIntegrationsIdRoute: AuthedAdminIntegrationsIdRoute,
  }

const AuthedAdminIntegrationsRouteWithChildren =
  AuthedAdminIntegrationsRoute._addFileChildren(
    AuthedAdminIntegrationsRouteChildren,
  )

interface AuthedAdminOnboardingRouteChildren {
  AuthedAdminOnboardingIdRoute: typeof AuthedAdminOnboardingIdRoute
}

const AuthedAdminOnboardingRouteChildren: AuthedAdminOnboardingRouteChildren = {
  AuthedAdminOnboardingIdRoute: AuthedAdminOnboardingIdRoute,
}

const AuthedAdminOnboardingRouteWithChildren =
  AuthedAdminOnboardingRoute._addFileChildren(
    AuthedAdminOnboardingRouteChildren,
  )

interface AuthedAdminRiskRouteChildren {
  AuthedAdminRiskIdRoute: typeof AuthedAdminRiskIdRoute
}

const AuthedAdminRiskRouteChildren: AuthedAdminRiskRouteChildren = {
  AuthedAdminRiskIdRoute: AuthedAdminRiskIdRoute,
}

const AuthedAdminRiskRouteWithChildren = AuthedAdminRiskRoute._addFileChildren(
  AuthedAdminRiskRouteChildren,
)

interface AuthedAdminStripeEventsRouteChildren {
  AuthedAdminStripeEventsIdRoute: typeof AuthedAdminStripeEventsIdRoute
}

const AuthedAdminStripeEventsRouteChildren: AuthedAdminStripeEventsRouteChildren =
  {
    AuthedAdminStripeEventsIdRoute: AuthedAdminStripeEventsIdRoute,
  }

const AuthedAdminStripeEventsRouteWithChildren =
  AuthedAdminStripeEventsRoute._addFileChildren(
    AuthedAdminStripeEventsRouteChildren,
  )

interface AuthedAdminUsersRouteChildren {
  AuthedAdminUsersIdRoute: typeof AuthedAdminUsersIdRoute
}

const AuthedAdminUsersRouteChildren: AuthedAdminUsersRouteChildren = {
  AuthedAdminUsersIdRoute: AuthedAdminUsersIdRoute,
}

const AuthedAdminUsersRouteWithChildren =
  AuthedAdminUsersRoute._addFileChildren(AuthedAdminUsersRouteChildren)

interface AuthedIbgIdRouteChildren {
  AuthedIbgIdAmendmentRoute: typeof AuthedIbgIdAmendmentRoute
}

const AuthedIbgIdRouteChildren: AuthedIbgIdRouteChildren = {
  AuthedIbgIdAmendmentRoute: AuthedIbgIdAmendmentRoute,
}

const AuthedIbgIdRouteWithChildren = AuthedIbgIdRoute._addFileChildren(
  AuthedIbgIdRouteChildren,
)

interface AuthedRouteChildren {
  AuthedCustomersRoute: typeof AuthedCustomersRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedFundingRoute: typeof AuthedFundingRouteWithChildren
  AuthedJobsRoute: typeof AuthedJobsRouteWithChildren
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedProjectsRoute: typeof AuthedProjectsRoute
  AuthedPropertiesRoute: typeof AuthedPropertiesRouteWithChildren
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedSubmissionsRoute: typeof AuthedSubmissionsRouteWithChildren
  AuthedAdminActivityRoute: typeof AuthedAdminActivityRoute
  AuthedAdminAmendmentsRoute: typeof AuthedAdminAmendmentsRouteWithChildren
  AuthedAdminAuditRoute: typeof AuthedAdminAuditRouteWithChildren
  AuthedAdminCompaniesRoute: typeof AuthedAdminCompaniesRouteWithChildren
  AuthedAdminConfigRoute: typeof AuthedAdminConfigRoute
  AuthedAdminCrmRoute: typeof AuthedAdminCrmRoute
  AuthedAdminCronRoute: typeof AuthedAdminCronRoute
  AuthedAdminEvidenceRequirementsRoute: typeof AuthedAdminEvidenceRequirementsRoute
  AuthedAdminExternalApisRoute: typeof AuthedAdminExternalApisRoute
  AuthedAdminFeatureFlagsRoute: typeof AuthedAdminFeatureFlagsRoute
  AuthedAdminFundingSchemesRoute: typeof AuthedAdminFundingSchemesRoute
  AuthedAdminInstallationTypesRoute: typeof AuthedAdminInstallationTypesRoute
  AuthedAdminIntegrationsRoute: typeof AuthedAdminIntegrationsRouteWithChildren
  AuthedAdminMeasureAccessRoute: typeof AuthedAdminMeasureAccessRoute
  AuthedAdminMeasurePolicyRoute: typeof AuthedAdminMeasurePolicyRoute
  AuthedAdminMembershipRoute: typeof AuthedAdminMembershipRoute
  AuthedAdminOnboardingRoute: typeof AuthedAdminOnboardingRouteWithChildren
  AuthedAdminPermissionsRoute: typeof AuthedAdminPermissionsRoute
  AuthedAdminRiskRoute: typeof AuthedAdminRiskRouteWithChildren
  AuthedAdminRiskOverridesRoute: typeof AuthedAdminRiskOverridesRoute
  AuthedAdminStripeEventsRoute: typeof AuthedAdminStripeEventsRouteWithChildren
  AuthedAdminSystemSettingsRoute: typeof AuthedAdminSystemSettingsRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRouteWithChildren
  AuthedIbgIdRoute: typeof AuthedIbgIdRouteWithChildren
  AuthedIbgHistoryRoute: typeof AuthedIbgHistoryRoute
  AuthedIbgNewRoute: typeof AuthedIbgNewRoute
  AuthedIbgRepositoryRoute: typeof AuthedIbgRepositoryRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCustomersRoute: AuthedCustomersRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedFundingRoute: AuthedFundingRouteWithChildren,
  AuthedJobsRoute: AuthedJobsRouteWithChildren,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedProjectsRoute: AuthedProjectsRoute,
  AuthedPropertiesRoute: AuthedPropertiesRouteWithChildren,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedSubmissionsRoute: AuthedSubmissionsRouteWithChildren,
  AuthedAdminActivityRoute: AuthedAdminActivityRoute,
  AuthedAdminAmendmentsRoute: AuthedAdminAmendmentsRouteWithChildren,
  AuthedAdminAuditRoute: AuthedAdminAuditRouteWithChildren,
  AuthedAdminCompaniesRoute: AuthedAdminCompaniesRouteWithChildren,
  AuthedAdminConfigRoute: AuthedAdminConfigRoute,
  AuthedAdminCrmRoute: AuthedAdminCrmRoute,
  AuthedAdminCronRoute: AuthedAdminCronRoute,
  AuthedAdminEvidenceRequirementsRoute: AuthedAdminEvidenceRequirementsRoute,
  AuthedAdminExternalApisRoute: AuthedAdminExternalApisRoute,
  AuthedAdminFeatureFlagsRoute: AuthedAdminFeatureFlagsRoute,
  AuthedAdminFundingSchemesRoute: AuthedAdminFundingSchemesRoute,
  AuthedAdminInstallationTypesRoute: AuthedAdminInstallationTypesRoute,
  AuthedAdminIntegrationsRoute: AuthedAdminIntegrationsRouteWithChildren,
  AuthedAdminMeasureAccessRoute: AuthedAdminMeasureAccessRoute,
  AuthedAdminMeasurePolicyRoute: AuthedAdminMeasurePolicyRoute,
  AuthedAdminMembershipRoute: AuthedAdminMembershipRoute,
  AuthedAdminOnboardingRoute: AuthedAdminOnboardingRouteWithChildren,
  AuthedAdminPermissionsRoute: AuthedAdminPermissionsRoute,
  AuthedAdminRiskRoute: AuthedAdminRiskRouteWithChildren,
  AuthedAdminRiskOverridesRoute: AuthedAdminRiskOverridesRoute,
  AuthedAdminStripeEventsRoute: AuthedAdminStripeEventsRouteWithChildren,
  AuthedAdminSystemSettingsRoute: AuthedAdminSystemSettingsRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRouteWithChildren,
  AuthedIbgIdRoute: AuthedIbgIdRouteWithChildren,
  AuthedIbgHistoryRoute: AuthedIbgHistoryRoute,
  AuthedIbgNewRoute: AuthedIbgNewRoute,
  AuthedIbgRepositoryRoute: AuthedIbgRepositoryRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  VerifyRoute: VerifyRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
