/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSubmissionsRouteImport } from './routes/_authed.submissions'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedPropertiesRouteImport } from './routes/_authed.properties'
import { Route as AuthedProjectsRouteImport } from './routes/_authed.projects'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed.onboarding'
import { Route as AuthedJobsRouteImport } from './routes/_authed.jobs'
import { Route as AuthedFundingRouteImport } from './routes/_authed.funding'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedCustomersRouteImport } from './routes/_authed.customers'
import { Route as AuthedSettingsSubscriptionRouteImport } from './routes/_authed.settings.subscription'
import { Route as AuthedSettingsProfileRouteImport } from './routes/_authed.settings.profile'
import { Route as AuthedSettingsNotificationsRouteImport } from './routes/_authed.settings.notifications'
import { Route as AuthedSettingsMeasuresRouteImport } from './routes/_authed.settings.measures'
import { Route as AuthedPropertiesIdRouteImport } from './routes/_authed.properties.$id'
import { Route as AuthedJobsNewRouteImport } from './routes/_authed.jobs.new'
import { Route as AuthedJobsIdRouteImport } from './routes/_authed.jobs.$id'
import { Route as AuthedIbgRepositoryRouteImport } from './routes/_authed.ibg.repository'
import { Route as AuthedIbgNewRouteImport } from './routes/_authed.ibg.new'
import { Route as AuthedIbgHistoryRouteImport } from './routes/_authed.ibg.history'
import { Route as AuthedIbgIdRouteImport } from './routes/_authed.ibg.$id'
import { Route as AuthedFundingMatchRouteImport } from './routes/_authed.funding.match'
import { Route as AuthedFundingIdRouteImport } from './routes/_authed.funding.$id'
import { Route as AuthedCustomersNewRouteImport } from './routes/_authed.customers.new'
import { Route as AuthedCustomersIdRouteImport } from './routes/_authed.customers.$id'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed.admin.users'
import { Route as AuthedAdminPermissionsRouteImport } from './routes/_authed.admin.permissions'
import { Route as AuthedAdminOnboardingRouteImport } from './routes/_authed.admin.onboarding'
import { Route as AuthedAdminConfigRouteImport } from './routes/_authed.admin.config'
import { Route as AuthedAdminAuditRouteImport } from './routes/_authed.admin.audit'
import { Route as AuthedAdminAmendmentsRouteImport } from './routes/_authed.admin.amendments'
import { Route as AuthedAdminActivityRouteImport } from './routes/_authed.admin.activity'
import { Route as AuthedIbgIdAmendmentRouteImport } from './routes/_authed.ibg.$id.amendment'
import { Route as AuthedAdminUsersIdRouteImport } from './routes/_authed.admin.users.$id'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSubmissionsRoute = AuthedSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPropertiesRoute = AuthedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsRoute = AuthedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsRoute = AuthedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFundingRoute = AuthedFundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCustomersRoute = AuthedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsSubscriptionRoute =
  AuthedSettingsSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsProfileRoute = AuthedSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsNotificationsRoute =
  AuthedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsMeasuresRoute = AuthedSettingsMeasuresRouteImport.update({
  id: '/measures',
  path: '/measures',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedPropertiesIdRoute = AuthedPropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedPropertiesRoute,
} as any)
const AuthedJobsNewRoute = AuthedJobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedJobsRoute,
} as any)
const AuthedJobsIdRoute = AuthedJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedJobsRoute,
} as any)
const AuthedIbgRepositoryRoute = AuthedIbgRepositoryRouteImport.update({
  id: '/ibg/repository',
  path: '/ibg/repository',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIbgNewRoute = AuthedIbgNewRouteImport.update({
  id: '/ibg/new',
  path: '/ibg/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIbgHistoryRoute = AuthedIbgHistoryRouteImport.update({
  id: '/ibg/history',
  path: '/ibg/history',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIbgIdRoute = AuthedIbgIdRouteImport.update({
  id: '/ibg/$id',
  path: '/ibg/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFundingMatchRoute = AuthedFundingMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AuthedFundingRoute,
} as any)
const AuthedFundingIdRoute = AuthedFundingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedFundingRoute,
} as any)
const AuthedCustomersNewRoute = AuthedCustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedCustomersRoute,
} as any)
const AuthedCustomersIdRoute = AuthedCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedCustomersRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminPermissionsRoute = AuthedAdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminOnboardingRoute = AuthedAdminOnboardingRouteImport.update({
  id: '/admin/onboarding',
  path: '/admin/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminConfigRoute = AuthedAdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminAuditRoute = AuthedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminAmendmentsRoute = AuthedAdminAmendmentsRouteImport.update({
  id: '/admin/amendments',
  path: '/admin/amendments',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminActivityRoute = AuthedAdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIbgIdAmendmentRoute = AuthedIbgIdAmendmentRouteImport.update({
  id: '/amendment',
  path: '/amendment',
  getParentRoute: () => AuthedIbgIdRoute,
} as any)
const AuthedAdminUsersIdRoute = AuthedAdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedAdminUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/customers': typeof AuthedCustomersRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/funding': typeof AuthedFundingRouteWithChildren
  '/jobs': typeof AuthedJobsRouteWithChildren
  '/onboarding': typeof AuthedOnboardingRoute
  '/projects': typeof AuthedProjectsRoute
  '/properties': typeof AuthedPropertiesRouteWithChildren
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/submissions': typeof AuthedSubmissionsRoute
  '/admin/activity': typeof AuthedAdminActivityRoute
  '/admin/amendments': typeof AuthedAdminAmendmentsRoute
  '/admin/audit': typeof AuthedAdminAuditRoute
  '/admin/config': typeof AuthedAdminConfigRoute
  '/admin/onboarding': typeof AuthedAdminOnboardingRoute
  '/admin/permissions': typeof AuthedAdminPermissionsRoute
  '/admin/users': typeof AuthedAdminUsersRouteWithChildren
  '/customers/$id': typeof AuthedCustomersIdRoute
  '/customers/new': typeof AuthedCustomersNewRoute
  '/funding/$id': typeof AuthedFundingIdRoute
  '/funding/match': typeof AuthedFundingMatchRoute
  '/ibg/$id': typeof AuthedIbgIdRouteWithChildren
  '/ibg/history': typeof AuthedIbgHistoryRoute
  '/ibg/new': typeof AuthedIbgNewRoute
  '/ibg/repository': typeof AuthedIbgRepositoryRoute
  '/jobs/$id': typeof AuthedJobsIdRoute
  '/jobs/new': typeof AuthedJobsNewRoute
  '/properties/$id': typeof AuthedPropertiesIdRoute
  '/settings/measures': typeof AuthedSettingsMeasuresRoute
  '/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
  '/settings/subscription': typeof AuthedSettingsSubscriptionRoute
  '/admin/users/$id': typeof AuthedAdminUsersIdRoute
  '/ibg/$id/amendment': typeof AuthedIbgIdAmendmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/customers': typeof AuthedCustomersRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/funding': typeof AuthedFundingRouteWithChildren
  '/jobs': typeof AuthedJobsRouteWithChildren
  '/onboarding': typeof AuthedOnboardingRoute
  '/projects': typeof AuthedProjectsRoute
  '/properties': typeof AuthedPropertiesRouteWithChildren
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/submissions': typeof AuthedSubmissionsRoute
  '/admin/activity': typeof AuthedAdminActivityRoute
  '/admin/amendments': typeof AuthedAdminAmendmentsRoute
  '/admin/audit': typeof AuthedAdminAuditRoute
  '/admin/config': typeof AuthedAdminConfigRoute
  '/admin/onboarding': typeof AuthedAdminOnboardingRoute
  '/admin/permissions': typeof AuthedAdminPermissionsRoute
  '/admin/users': typeof AuthedAdminUsersRouteWithChildren
  '/customers/$id': typeof AuthedCustomersIdRoute
  '/customers/new': typeof AuthedCustomersNewRoute
  '/funding/$id': typeof AuthedFundingIdRoute
  '/funding/match': typeof AuthedFundingMatchRoute
  '/ibg/$id': typeof AuthedIbgIdRouteWithChildren
  '/ibg/history': typeof AuthedIbgHistoryRoute
  '/ibg/new': typeof AuthedIbgNewRoute
  '/ibg/repository': typeof AuthedIbgRepositoryRoute
  '/jobs/$id': typeof AuthedJobsIdRoute
  '/jobs/new': typeof AuthedJobsNewRoute
  '/properties/$id': typeof AuthedPropertiesIdRoute
  '/settings/measures': typeof AuthedSettingsMeasuresRoute
  '/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
  '/settings/subscription': typeof AuthedSettingsSubscriptionRoute
  '/admin/users/$id': typeof AuthedAdminUsersIdRoute
  '/ibg/$id/amendment': typeof AuthedIbgIdAmendmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/customers': typeof AuthedCustomersRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/funding': typeof AuthedFundingRouteWithChildren
  '/_authed/jobs': typeof AuthedJobsRouteWithChildren
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_authed/projects': typeof AuthedProjectsRoute
  '/_authed/properties': typeof AuthedPropertiesRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRouteWithChildren
  '/_authed/submissions': typeof AuthedSubmissionsRoute
  '/_authed/admin/activity': typeof AuthedAdminActivityRoute
  '/_authed/admin/amendments': typeof AuthedAdminAmendmentsRoute
  '/_authed/admin/audit': typeof AuthedAdminAuditRoute
  '/_authed/admin/config': typeof AuthedAdminConfigRoute
  '/_authed/admin/onboarding': typeof AuthedAdminOnboardingRoute
  '/_authed/admin/permissions': typeof AuthedAdminPermissionsRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRouteWithChildren
  '/_authed/customers/$id': typeof AuthedCustomersIdRoute
  '/_authed/customers/new': typeof AuthedCustomersNewRoute
  '/_authed/funding/$id': typeof AuthedFundingIdRoute
  '/_authed/funding/match': typeof AuthedFundingMatchRoute
  '/_authed/ibg/$id': typeof AuthedIbgIdRouteWithChildren
  '/_authed/ibg/history': typeof AuthedIbgHistoryRoute
  '/_authed/ibg/new': typeof AuthedIbgNewRoute
  '/_authed/ibg/repository': typeof AuthedIbgRepositoryRoute
  '/_authed/jobs/$id': typeof AuthedJobsIdRoute
  '/_authed/jobs/new': typeof AuthedJobsNewRoute
  '/_authed/properties/$id': typeof AuthedPropertiesIdRoute
  '/_authed/settings/measures': typeof AuthedSettingsMeasuresRoute
  '/_authed/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/_authed/settings/profile': typeof AuthedSettingsProfileRoute
  '/_authed/settings/subscription': typeof AuthedSettingsSubscriptionRoute
  '/_authed/admin/users/$id': typeof AuthedAdminUsersIdRoute
  '/_authed/ibg/$id/amendment': typeof AuthedIbgIdAmendmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/customers'
    | '/dashboard'
    | '/funding'
    | '/jobs'
    | '/onboarding'
    | '/projects'
    | '/properties'
    | '/settings'
    | '/submissions'
    | '/admin/activity'
    | '/admin/amendments'
    | '/admin/audit'
    | '/admin/config'
    | '/admin/onboarding'
    | '/admin/permissions'
    | '/admin/users'
    | '/customers/$id'
    | '/customers/new'
    | '/funding/$id'
    | '/funding/match'
    | '/ibg/$id'
    | '/ibg/history'
    | '/ibg/new'
    | '/ibg/repository'
    | '/jobs/$id'
    | '/jobs/new'
    | '/properties/$id'
    | '/settings/measures'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/subscription'
    | '/admin/users/$id'
    | '/ibg/$id/amendment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/customers'
    | '/dashboard'
    | '/funding'
    | '/jobs'
    | '/onboarding'
    | '/projects'
    | '/properties'
    | '/settings'
    | '/submissions'
    | '/admin/activity'
    | '/admin/amendments'
    | '/admin/audit'
    | '/admin/config'
    | '/admin/onboarding'
    | '/admin/permissions'
    | '/admin/users'
    | '/customers/$id'
    | '/customers/new'
    | '/funding/$id'
    | '/funding/match'
    | '/ibg/$id'
    | '/ibg/history'
    | '/ibg/new'
    | '/ibg/repository'
    | '/jobs/$id'
    | '/jobs/new'
    | '/properties/$id'
    | '/settings/measures'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/subscription'
    | '/admin/users/$id'
    | '/ibg/$id/amendment'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/pricing'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/customers'
    | '/_authed/dashboard'
    | '/_authed/funding'
    | '/_authed/jobs'
    | '/_authed/onboarding'
    | '/_authed/projects'
    | '/_authed/properties'
    | '/_authed/settings'
    | '/_authed/submissions'
    | '/_authed/admin/activity'
    | '/_authed/admin/amendments'
    | '/_authed/admin/audit'
    | '/_authed/admin/config'
    | '/_authed/admin/onboarding'
    | '/_authed/admin/permissions'
    | '/_authed/admin/users'
    | '/_authed/customers/$id'
    | '/_authed/customers/new'
    | '/_authed/funding/$id'
    | '/_authed/funding/match'
    | '/_authed/ibg/$id'
    | '/_authed/ibg/history'
    | '/_authed/ibg/new'
    | '/_authed/ibg/repository'
    | '/_authed/jobs/$id'
    | '/_authed/jobs/new'
    | '/_authed/properties/$id'
    | '/_authed/settings/measures'
    | '/_authed/settings/notifications'
    | '/_authed/settings/profile'
    | '/_authed/settings/subscription'
    | '/_authed/admin/users/$id'
    | '/_authed/ibg/$id/amendment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/submissions': {
      id: '/_authed/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthedSubmissionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/properties': {
      id: '/_authed/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthedPropertiesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects': {
      id: '/_authed/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthedProjectsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs': {
      id: '/_authed/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthedJobsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/funding': {
      id: '/_authed/funding'
      path: '/funding'
      fullPath: '/funding'
      preLoaderRoute: typeof AuthedFundingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/customers': {
      id: '/_authed/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthedCustomersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/subscription': {
      id: '/_authed/settings/subscription'
      path: '/subscription'
      fullPath: '/settings/subscription'
      preLoaderRoute: typeof AuthedSettingsSubscriptionRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/profile': {
      id: '/_authed/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthedSettingsProfileRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/notifications': {
      id: '/_authed/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthedSettingsNotificationsRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/measures': {
      id: '/_authed/settings/measures'
      path: '/measures'
      fullPath: '/settings/measures'
      preLoaderRoute: typeof AuthedSettingsMeasuresRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/properties/$id': {
      id: '/_authed/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof AuthedPropertiesIdRouteImport
      parentRoute: typeof AuthedPropertiesRoute
    }
    '/_authed/jobs/new': {
      id: '/_authed/jobs/new'
      path: '/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AuthedJobsNewRouteImport
      parentRoute: typeof AuthedJobsRoute
    }
    '/_authed/jobs/$id': {
      id: '/_authed/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AuthedJobsIdRouteImport
      parentRoute: typeof AuthedJobsRoute
    }
    '/_authed/ibg/repository': {
      id: '/_authed/ibg/repository'
      path: '/ibg/repository'
      fullPath: '/ibg/repository'
      preLoaderRoute: typeof AuthedIbgRepositoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ibg/new': {
      id: '/_authed/ibg/new'
      path: '/ibg/new'
      fullPath: '/ibg/new'
      preLoaderRoute: typeof AuthedIbgNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ibg/history': {
      id: '/_authed/ibg/history'
      path: '/ibg/history'
      fullPath: '/ibg/history'
      preLoaderRoute: typeof AuthedIbgHistoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ibg/$id': {
      id: '/_authed/ibg/$id'
      path: '/ibg/$id'
      fullPath: '/ibg/$id'
      preLoaderRoute: typeof AuthedIbgIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/funding/match': {
      id: '/_authed/funding/match'
      path: '/match'
      fullPath: '/funding/match'
      preLoaderRoute: typeof AuthedFundingMatchRouteImport
      parentRoute: typeof AuthedFundingRoute
    }
    '/_authed/funding/$id': {
      id: '/_authed/funding/$id'
      path: '/$id'
      fullPath: '/funding/$id'
      preLoaderRoute: typeof AuthedFundingIdRouteImport
      parentRoute: typeof AuthedFundingRoute
    }
    '/_authed/customers/new': {
      id: '/_authed/customers/new'
      path: '/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AuthedCustomersNewRouteImport
      parentRoute: typeof AuthedCustomersRoute
    }
    '/_authed/customers/$id': {
      id: '/_authed/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthedCustomersIdRouteImport
      parentRoute: typeof AuthedCustomersRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/permissions': {
      id: '/_authed/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthedAdminPermissionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/onboarding': {
      id: '/_authed/admin/onboarding'
      path: '/admin/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AuthedAdminOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/config': {
      id: '/_authed/admin/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AuthedAdminConfigRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/audit': {
      id: '/_authed/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthedAdminAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/amendments': {
      id: '/_authed/admin/amendments'
      path: '/admin/amendments'
      fullPath: '/admin/amendments'
      preLoaderRoute: typeof AuthedAdminAmendmentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/activity': {
      id: '/_authed/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthedAdminActivityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/ibg/$id/amendment': {
      id: '/_authed/ibg/$id/amendment'
      path: '/amendment'
      fullPath: '/ibg/$id/amendment'
      preLoaderRoute: typeof AuthedIbgIdAmendmentRouteImport
      parentRoute: typeof AuthedIbgIdRoute
    }
    '/_authed/admin/users/$id': {
      id: '/_authed/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthedAdminUsersIdRouteImport
      parentRoute: typeof AuthedAdminUsersRoute
    }
  }
}

interface AuthedCustomersRouteChildren {
  AuthedCustomersIdRoute: typeof AuthedCustomersIdRoute
  AuthedCustomersNewRoute: typeof AuthedCustomersNewRoute
}

const AuthedCustomersRouteChildren: AuthedCustomersRouteChildren = {
  AuthedCustomersIdRoute: AuthedCustomersIdRoute,
  AuthedCustomersNewRoute: AuthedCustomersNewRoute,
}

const AuthedCustomersRouteWithChildren = AuthedCustomersRoute._addFileChildren(
  AuthedCustomersRouteChildren,
)

interface AuthedFundingRouteChildren {
  AuthedFundingIdRoute: typeof AuthedFundingIdRoute
  AuthedFundingMatchRoute: typeof AuthedFundingMatchRoute
}

const AuthedFundingRouteChildren: AuthedFundingRouteChildren = {
  AuthedFundingIdRoute: AuthedFundingIdRoute,
  AuthedFundingMatchRoute: AuthedFundingMatchRoute,
}

const AuthedFundingRouteWithChildren = AuthedFundingRoute._addFileChildren(
  AuthedFundingRouteChildren,
)

interface AuthedJobsRouteChildren {
  AuthedJobsIdRoute: typeof AuthedJobsIdRoute
  AuthedJobsNewRoute: typeof AuthedJobsNewRoute
}

const AuthedJobsRouteChildren: AuthedJobsRouteChildren = {
  AuthedJobsIdRoute: AuthedJobsIdRoute,
  AuthedJobsNewRoute: AuthedJobsNewRoute,
}

const AuthedJobsRouteWithChildren = AuthedJobsRoute._addFileChildren(
  AuthedJobsRouteChildren,
)

interface AuthedPropertiesRouteChildren {
  AuthedPropertiesIdRoute: typeof AuthedPropertiesIdRoute
}

const AuthedPropertiesRouteChildren: AuthedPropertiesRouteChildren = {
  AuthedPropertiesIdRoute: AuthedPropertiesIdRoute,
}

const AuthedPropertiesRouteWithChildren =
  AuthedPropertiesRoute._addFileChildren(AuthedPropertiesRouteChildren)

interface AuthedSettingsRouteChildren {
  AuthedSettingsMeasuresRoute: typeof AuthedSettingsMeasuresRoute
  AuthedSettingsNotificationsRoute: typeof AuthedSettingsNotificationsRoute
  AuthedSettingsProfileRoute: typeof AuthedSettingsProfileRoute
  AuthedSettingsSubscriptionRoute: typeof AuthedSettingsSubscriptionRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsMeasuresRoute: AuthedSettingsMeasuresRoute,
  AuthedSettingsNotificationsRoute: AuthedSettingsNotificationsRoute,
  AuthedSettingsProfileRoute: AuthedSettingsProfileRoute,
  AuthedSettingsSubscriptionRoute: AuthedSettingsSubscriptionRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedAdminUsersRouteChildren {
  AuthedAdminUsersIdRoute: typeof AuthedAdminUsersIdRoute
}

const AuthedAdminUsersRouteChildren: AuthedAdminUsersRouteChildren = {
  AuthedAdminUsersIdRoute: AuthedAdminUsersIdRoute,
}

const AuthedAdminUsersRouteWithChildren =
  AuthedAdminUsersRoute._addFileChildren(AuthedAdminUsersRouteChildren)

interface AuthedIbgIdRouteChildren {
  AuthedIbgIdAmendmentRoute: typeof AuthedIbgIdAmendmentRoute
}

const AuthedIbgIdRouteChildren: AuthedIbgIdRouteChildren = {
  AuthedIbgIdAmendmentRoute: AuthedIbgIdAmendmentRoute,
}

const AuthedIbgIdRouteWithChildren = AuthedIbgIdRoute._addFileChildren(
  AuthedIbgIdRouteChildren,
)

interface AuthedRouteChildren {
  AuthedCustomersRoute: typeof AuthedCustomersRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedFundingRoute: typeof AuthedFundingRouteWithChildren
  AuthedJobsRoute: typeof AuthedJobsRouteWithChildren
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedProjectsRoute: typeof AuthedProjectsRoute
  AuthedPropertiesRoute: typeof AuthedPropertiesRouteWithChildren
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedSubmissionsRoute: typeof AuthedSubmissionsRoute
  AuthedAdminActivityRoute: typeof AuthedAdminActivityRoute
  AuthedAdminAmendmentsRoute: typeof AuthedAdminAmendmentsRoute
  AuthedAdminAuditRoute: typeof AuthedAdminAuditRoute
  AuthedAdminConfigRoute: typeof AuthedAdminConfigRoute
  AuthedAdminOnboardingRoute: typeof AuthedAdminOnboardingRoute
  AuthedAdminPermissionsRoute: typeof AuthedAdminPermissionsRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRouteWithChildren
  AuthedIbgIdRoute: typeof AuthedIbgIdRouteWithChildren
  AuthedIbgHistoryRoute: typeof AuthedIbgHistoryRoute
  AuthedIbgNewRoute: typeof AuthedIbgNewRoute
  AuthedIbgRepositoryRoute: typeof AuthedIbgRepositoryRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCustomersRoute: AuthedCustomersRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedFundingRoute: AuthedFundingRouteWithChildren,
  AuthedJobsRoute: AuthedJobsRouteWithChildren,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedProjectsRoute: AuthedProjectsRoute,
  AuthedPropertiesRoute: AuthedPropertiesRouteWithChildren,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedSubmissionsRoute: AuthedSubmissionsRoute,
  AuthedAdminActivityRoute: AuthedAdminActivityRoute,
  AuthedAdminAmendmentsRoute: AuthedAdminAmendmentsRoute,
  AuthedAdminAuditRoute: AuthedAdminAuditRoute,
  AuthedAdminConfigRoute: AuthedAdminConfigRoute,
  AuthedAdminOnboardingRoute: AuthedAdminOnboardingRoute,
  AuthedAdminPermissionsRoute: AuthedAdminPermissionsRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRouteWithChildren,
  AuthedIbgIdRoute: AuthedIbgIdRouteWithChildren,
  AuthedIbgHistoryRoute: AuthedIbgHistoryRoute,
  AuthedIbgNewRoute: AuthedIbgNewRoute,
  AuthedIbgRepositoryRoute: AuthedIbgRepositoryRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
